# Generated by Django 5.0.6 on 2024-08-04 14:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interaction",
            name="timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
