# Generated by Django 5.0.6 on 2024-08-08 20:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="authentication_type",
            field=models.CharField(
                choices=[("manual", "Manual"), ("google", "Google")],
                default="manual",
                max_length=50,
            ),
        ),
    ]
