# Generated by Django 5.0.6 on 2024-08-21 10:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0003_customuser_receive_marketing_emails"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="receive_marketing_emails",
        ),
    ]
