# Generated by Django 5.0.6 on 2024-10-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="meeting_status",
            field=models.CharField(
                choices=[("scheduled", "Scheduled"), ("completed", "Completed")],
                max_length=50,
            ),
        ),
    ]
