# Generated by Django 5.0.6 on 2024-07-02 19:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="company",
            old_name="bio",
            new_name="company_description",
        ),
    ]
