# Generated by Django 5.0.6 on 2024-08-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="company_logo",
            field=models.URLField(blank=True, null=True),
        ),
    ]
