# Generated by Django 5.0.6 on 2024-08-08 20:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0002_alter_company_company_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="profile_pic",
            field=models.URLField(blank=True, null=True),
        ),
    ]
