# Generated by Django 5.0.6 on 2024-07-12 21:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0002_employee_address_employee_bio_employee_facebook_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="profile_pic",
        ),
        migrations.AddField(
            model_name="company",
            name="company_logo",
            field=models.ImageField(blank=True, null=True, upload_to="company_logo/"),
        ),
        migrations.AddField(
            model_name="company",
            name="linkedin",
            field=models.URLField(blank=True, null=True),
        ),
    ]
