# Generated by Django 5.0.6 on 2024-07-15 15:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0003_remove_company_profile_pic_company_company_logo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="registration_token",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
