# Generated by Django 5.0.6 on 2024-08-21 10:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0004_alter_company_address_alter_company_admin_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="receive_marketing_emails",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="employee",
            name="receive_marketing_emails",
            field=models.BooleanField(default=False),
        ),
    ]
