# Generated by Django 5.0.6 on 2024-07-15 20:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0005_alter_employee_registration_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="registration_token",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
