# Generated by Django 5.0.6 on 2024-09-03 10:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0006_employee_display_email_alter_employee_whatsapp"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="username",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
