# Generated by Django 5.0.6 on 2024-09-04 08:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0007_employee_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="username",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
