# Generated by Django 5.0.6 on 2024-07-17 14:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0008_alter_employee_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="user",
        ),
    ]
