# Generated by Django 5.0.6 on 2024-09-10 10:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0008_company_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="display_email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
