# Generated by Django 5.0.6 on 2024-10-19 18:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0009_company_display_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="display_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
