# Generated by Django 5.0.6 on 2024-07-12 19:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("individual", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="github",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="whatsapp",
            field=models.URLField(blank=True, null=True),
        ),
    ]
