# Generated by Django 5.0.6 on 2024-07-12 19:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("individual", "0002_userprofile_github_userprofile_website_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="whatsapp",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
