# Generated by Django 5.0.6 on 2024-07-26 16:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("individual", "0003_alter_userprofile_whatsapp"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="position",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
