# Generated by Django 5.0.6 on 2024-08-19 10:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("individual", "0003_receivedprofile_shared_from_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="receivedprofile",
            name="shared_from_email",
        ),
        migrations.AlterField(
            model_name="receivedprofile",
            name="shared_from",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
