# Generated by Django 5.0.6 on 2024-08-21 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("individual", "0005_receivedprofile_shared_from_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="receive_marketing_emails",
            field=models.BooleanField(default=False),
        ),
    ]
