# Generated by Django 5.0.6 on 2024-09-01 09:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("individual", "0006_userprofile_receive_marketing_emails"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="whatsapp",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
