# Generated by Django 5.0.6 on 2024-09-03 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("individual", "0007_alter_userprofile_whatsapp"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="display_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="username",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
