# Generated by Django 5.0.6 on 2024-10-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("individual", "0011_receivedprofile_shared_from_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="receivedprofile",
            name="company_logo",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="receivedprofile",
            name="profile_pic",
            field=models.URLField(blank=True, null=True),
        ),
    ]
