# Generated by Django 5.0.6 on 2024-10-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("individual", "0012_receivedprofile_company_logo_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="receivedprofile",
            old_name="company_logo",
            new_name="shared_from_company_logo",
        ),
        migrations.RenameField(
            model_name="receivedprofile",
            old_name="profile_pic",
            new_name="shared_from_profile_pic",
        ),
        migrations.AddField(
            model_name="receivedprofile",
            name="shared_from_company_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="receivedprofile",
            name="shared_from_first_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="receivedprofile",
            name="shared_from_last_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="receivedprofile",
            name="shared_from_position",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
