# Generated by Django 5.0.6 on 2024-08-21 12:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("my_admin", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Events",
            new_name="Event",
        ),
    ]
