# Generated by Django 5.0.6 on 2024-08-22 10:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("my_admin", "0002_rename_events_event"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="event_longitute",
            new_name="event_longitude",
        ),
        migrations.RemoveField(
            model_name="event",
            name="attendees",
        ),
    ]
