name: Django CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Build Docker image
      run: |
        docker build -t onesec-api-project .

    - name: Copy files to EC2
      run: |
        scp -i ~/.ssh/id_rsa -r ./* ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/nfc-backend

    - name: SSH into EC2 and deploy
      run: |
        ssh -i ~/.ssh/id_rsa ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
        cd /home/ubuntu/nfc-backend
        
        # Stop and remove the existing container
        sudo docker stop onesec-api-project || true
        sudo docker rm onesec-api-project || true
        
        # Rebuild and run the Docker container
        sudo docker build -t onesec-api-project .
        sudo docker run -d -p 8000:8000 --name onesec-api-project onesec-api-project
        
        # Check the logs for troubleshooting
        sudo docker logs onesec-api-project
        
        # Exit the SSH session
        exit
        EOF
