name: Django CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH agent
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Add EC2 to known_hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Copy files to EC2
      run: |
        scp -r ./ ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/nfc-backend

    - name: SSH into EC2 and deploy
      run: |
        ssh ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
        cd /home/ubuntu/nfc-backend
        docker stop onesec-api-project || :
        docker rm onesec-api-project || :
        docker build -t onesec-api-project .
        docker run -d -p 8000:8000 --name onesec-api-project onesec-api-project
        EOF
