name: Django CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH agent
      uses: webfactory/ssh-agent@v0.8.1
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Copy files to EC2
      run: |
        scp -r ./ ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/app

    - name: SSH into EC2 and deploy
      run: |
        ssh ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
        cd /home/ubuntu/app
        docker stop django-app || :
        docker rm django-app || :
        docker build -t django-app .
        docker run -d -p 8000:8000 --name django-app django-app
        EOF
